<?php
/**
 * Configuration file — generated by install.php during setup.
 * You can edit these values manually afterwards (or via the admin panel).
 */
return array(
    'db_host' => 'localhost',
    'db_name' => '',
    'db_user' => '',
    'db_pass' => '',
    'db_port' => '3306',
    'base_url' => 'http://localhost',
    'timezone' => 'Asia/Tehran',
);
