<?php
/**
 * Configuration generated by install.php — 2026-08-15 07:58
 */
return array (
  'db_host' => 'localhost',
  'db_name' => 'cv',
  'db_user' => 'root',
  'db_pass' => '',
  'db_port' => '3306',
  'base_url' => 'http://127.0.0.1/cv',
  'timezone' => 'Asia/Tehran',
);
